from telegram import Emoji

countries_rk = [["Afghanistan"],
                ["Albania"],
                ["Algeria"],
                ["American Samoa"],
                ["Andorra"],
                ["Angola"],
                ["Anguilla"],
                ["Antarctica"],
                ["Antigua and Barbuda"],
                ["Argentina"],
                ["Armenia"],
                ["Aruba"],
                ["Australia"],
                ["Austria"],
                ["Azerbaijan"],
                ["Bahamas"],
                ["Bahrain"],
                ["Bangladesh"],
                ["Barbados"],
                ["Belarus"],
                ["Belgium"],
                ["Belize"],
                ["Benin"],
                ["Bermuda"],
                ["Bhutan"],
                ["Bolivia"],
                ["Bosnia and Herzegovina"],
                ["Botswana"],
                ["Brazil"],
                ["British Indian Ocean Territory"],
                ["Brunei Darussalam"],
                ["Bulgaria"],
                ["Burkina Faso"],
                ["Burundi"],
                ["Cambodia"],
                ["Cameroon"],
                ["Canada"],
                ["Central African Republic"],
                ["Chad"],
                ["Chile"],
                ["China"],
                ["Colombia"],
                ["Comoros"],
                ["Congo"],
                ["Costa Rica"],
                ["Cote D'Ivoire (Ivory Coast)"],
                ["Croatia (Hrvatska"],
                ["Cuba"],
                ["Cyprus"],
                ["Czech Republic"],
                ["Denmark"],
                ["Djibouti"],
                ["Dominica"],
                ["Dominican Republic"],
                ["Ecuador"],
                ["Egypt"],
                ["El Salvador"],
                ["Equatorial Guinea"],
                ["Eritrea"],
                ["Estonia"],
                ["Ethiopia"],
                ["Fiji"],
                ["Finland"],
                ["France"],
                ["France, Metropolitan"],
                ["French Guiana"],
                ["French Polynesia"],
                ["French Southern Territories"],
                ["Gabon"],
                ["Gambia"],
                ["Georgia"],
                ["Germany"],
                ["Ghana"],
                ["Gibraltar"],
                ["Greece"],
                ["Greenland"],
                ["Grenada"],
                ["Guadeloupe"],
                ["Guam"],
                ["Guatemala"],
                ["Guinea"],
                ["Guinea-Bissau"],
                ["Guyana"],
                ["Haiti"],
                ["Honduras"],
                ["Hong Kong"],
                ["Hungary"],
                ["Iceland"],
                ["India"],
                ["Indonesia"],
                ["Iran"],
                ["Iraq"],
                ["Ireland"],
                ["Israel"],
                ["Italy"],
                ["Jamaica"],
                ["Japan"],
                ["Jordan"],
                ["Kazakhstan"],
                ["Kenya"],
                ["Kiribati"],
                ["Korea (North)"],
                ["Korea (South)"],
                ["Kuwait"],
                ["Kyrgyzstan"],
                ["Laos"],
                ["Latvia"],
                ["Lebanon"],
                ["Lesotho"],
                ["Liberia"],
                ["Libya"],
                ["Liechtenstein"],
                ["Lithuania"],
                ["Luxembourg"],
                ["Macau"],
                ["Macedonia"],
                ["Madagascar"],
                ["Malawi"],
                ["Malaysia"],
                ["Maldives"],
                ["Mali"],
                ["Malta"],
                ["Martinique"],
                ["Mauritania"],
                ["Mauritius"],
                ["Mexico"],
                ["Micronesia"],
                ["Moldova"],
                ["Monaco"],
                ["Mongolia"],
                ["Montserrat"],
                ["Morocco"],
                ["Mozambique"],
                ["Myanmar"],
                ["Namibia"],
                ["Nauru"],
                ["Nepal"],
                ["Netherlands"],
                ["Netherlands Antilles"],
                ["New Caledonia"],
                ["New Zealand"],
                ["Nicaragua"],
                ["Niger"],
                ["Nigeria"],
                ["Norway"],
                ["Oman"],
                ["Pakistan"],
                ["Palau"],
                ["Panama"],
                ["Papua New Guinea"],
                ["Paraguay"],
                ["Peru"],
                ["Philippines"],
                ["Pitcairn"],
                ["Poland"],
                ["Portugal"],
                ["Puerto Rico"],
                ["Qatar"],
                ["Reunion"],
                ["Romania"],
                ["Russian Federation"],
                ["Rwanda"],
                ["Saint Kitts and Nevis"],
                ["Saint Lucia"],
                ["Saint Vincent and The Grenadines"],
                ["Samoa"],
                ["San Marino"],
                ["Sao Tome and Principe"],
                ["Saudi Arabia"],
                ["Senegal"],
                ["Seychelles"],
                ["Sierra Leone"],
                ["Singapore"],
                ["Slovak Republic"],
                ["Slovenia"],
                ["Somalia"],
                ["South Africa"],
                ["Spain"],
                ["Sri Lanka"],
                ["St. Helena"],
                ["St. Pierre and Miquelon"],
                ["Sudan"],
                ["Suriname"],
                ["Swaziland"],
                ["Sweden"],
                ["Switzerland"],
                ["Syria"],
                ["Taiwan"],
                ["Tajikistan"],
                ["Tanzania"],
                ["Thailand"],
                ["Togo"],
                ["Tokelau"],
                ["Tonga"],
                ["Trinidad and Tobago"],
                ["Tunisia"],
                ["Turkey"],
                ["Turkmenistan"],
                ["Tuvalu"],
                ["Uganda"],
                ["Ukraine"],
                ["United Arab Emirates"],
                ["United Kingdom"],
                ["United States"],
                ["Uruguay"],
                ["Uzbekistan"],
                ["Vanuatu"],
                ["Vatican City State (Holy See)"],
                ["Venezuela"],
                ["Vietnam"],
                ["Western Sahara"],
                ["Yemen"],
                ["Zaire"],
                ["Zambia"],
                ["Zimbabwe"]]

smiley_scale_5 = [[Emoji.TIRED_FACE], [Emoji.PERSON_FROWNING]]

languages = [["Deutsch"], ["English"], ["Espagnol"], ["Francais"]]


CUSTOM_KEYBOARDS = dict()
CUSTOM_KEYBOARDS['KEY_1'] = languages
CUSTOM_KEYBOARDS['KEY_2'] = countries_rk


def get_preset_by_choice(choice):
    return CUSTOM_KEYBOARDS[choice]
